{% set version = "1.7-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mcmcpack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MCMCpack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MCMCpack/MCMCpack_{{ version }}.tar.gz
  sha256: 3b0b46746324197c38826cde06729f031311c3520d9d42815b7b356d29b58529

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-coda >=0.11_3              # [build_platform != target_platform]
    - r-lattice                    # [build_platform != target_platform]
    - r-mcmc                       # [build_platform != target_platform]
    - r-quantreg                   # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-coda >=0.11_3
    - r-lattice
    - r-mcmc
    - r-quantreg
  run:
    - r-base
    - r-mass
    - r-coda >=0.11_3
    - r-lattice
    - r-mcmc
    - r-quantreg

test:
  commands:
    - $R -e "library('MCMCpack')"           # [not win]
    - "\"%R%\" -e \"library('MCMCpack')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MCMCpack
  dev_url: https://github.com/cran/MCMCpack
  license: GPL-3.0-only
  summary: Contains functions to perform Bayesian inference using posterior simulation for a number of statistical models. Most simulation is done in compiled C++ written in the Scythe Statistical Library Version 1.0.3. All models return 'coda' mcmc objects that can then be summarized using the 'coda' package. Some useful
    utility functions such as density functions, pseudo-random number generators for statistical distributions, a general purpose Metropolis sampling algorithm, and tools for visualization are provided.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
