{% set version = '1.4-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mcmcpack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MCMCpack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MCMCpack/MCMCpack_{{ version }}.tar.gz
  sha256: 97e193d628f7161e59288ed594a313af3a520bf30d5a95f1ede0cb2a567cf9f7

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-coda >=0.11_3
    - r-lattice
    - r-mcmc
    - r-quantreg
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-coda >=0.11_3
    - r-lattice
    - r-mcmc
    - r-quantreg

test:
  commands:
    - $R -e "library('MCMCpack')"           # [not win]
    - "\"%R%\" -e \"library('MCMCpack')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MCMCpack
  license: GPL-3
  summary: Contains functions to perform Bayesian inference using posterior simulation for a
    number of statistical models. Most simulation is done in compiled C++ written in
    the Scythe Statistical Library Version 1.0.3. All models return 'coda' mcmc objects
    that can then be summarized using the 'coda' package. Some useful utility functions
    such as density functions, pseudo-random number generators for statistical distributions,
    a general purpose Metropolis sampling algorithm, and tools for visualization are
    provided.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: MCMCpack
# Version: 1.4-4
# Date: 2018-09-14
# Title: Markov Chain Monte Carlo (MCMC) Package
# Author: Andrew D. Martin [aut], Kevin M. Quinn [aut], Jong Hee Park [aut,cre], Ghislain Vieilledent [ctb], Michael Malecki[ctb], Matthew Blackwell [ctb], Keith Poole [ctb], Craig Reed [ctb], Ben Goodrich [ctb], Ross Ihaka [cph], The R Development Core Team [cph], The R Foundation [cph], Pierre L'Ecuyer [cph], Makoto Matsumoto [cph], Takuji Nishimura [cph]
# Maintainer: Jong Hee Park <jongheepark@snu.ac.kr>
# Depends: R (>= 2.10.0), coda (>= 0.11-3), MASS, stats
# Imports: graphics, grDevices, lattice, methods, utils, mcmc, quantreg
# Description: Contains functions to perform Bayesian inference using posterior simulation for a number of statistical models. Most simulation is done in compiled C++ written in the Scythe Statistical Library Version 1.0.3. All models return 'coda' mcmc objects that can then be summarized using the 'coda' package. Some useful utility functions such as density functions, pseudo-random number generators for statistical distributions, a general purpose Metropolis sampling algorithm, and tools for visualization are provided.
# License: GPL-3
# SystemRequirements: gcc (>= 4.0)
# URL: https://CRAN.R-project.org/package=MCMCpack
# Packaged: 2018-09-14 02:12:54 UTC; park
# NeedsCompilation: yes
# Repository: CRAN
# RoxygenNote: 6.0.1
# Date/Publication: 2018-09-14 05:30:09 UTC
