travis:
  secure:
    BINSTAR_TOKEN: qv5srwxGuVp7YJcl/1wskLyh7JZDQ68AUBS0+Rc9XylJr6isnqFFy1rNhiX41s9dJm3Di+6en70ErtC23a1PpOzdXAnWYkqgP4z+Z7Zm27dkNSM9Cq7Vn3jzcbiMYuouzxeV8nTKQ+erK765ZHtSBHV9BiKu09Ag2IgMxadN1d7sAabjQhKyN9mtSW2r+rHJutEtanAHbQgdqCYgPJ5AAD9KO2STD+kb8/o0GNemlCVBQkc1wuyZTcbutbJZHZKM3KOOKL4x1iNZrk6qZB3XWu2hw7jhqSGp7ylBAGcquqfbUkaF62ClMN61I8PA59PHLsjzmUD9466Q+47EU0NQB8QNNm6CsTtyHjNEiRV7iN4TxkhRPHi59NJPW+xQAF7RJlxf1440guhta704sucUEJxss+WyeNZpNMPDfsegOmb9YTXXxGvuMjuv3LajhC/nsZi2YkfDnGEcLSVTeaDYBpkut4soAGn/F84k+gPMTLepVLW3c/usTDx04M9UX5evDbdzf7HeTJyf7cB8l48UNjJx/QrqzgjZ2n4uG6LSy9GWPmACnbC6PIWiEyDD8PiJ36wNGOD+ThxHW3QxTDbk0SiZph1sZWHWq89f7tMHJgfk/GqfmRbm6pK0WsHvK6POsp8A4tP8cQ4Fr/QokpHM4g0mzR6fkYenREz32KeLFqo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
