appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZI38Ru93QWkFIe+777xtwWsq9tqzeQUO4i07oahPnHjWmDKIdqdCLBkFwwpTyrGOBP5BHpORoyLNonKa/XooKwjUz3is4OcYHXsCnv1QkRS/OXoCaVyaCaN2luvITmHm4Rk6lWw5uvp+ZVyI5dOrBsse0RhrOGENZiJcjJlBkazhs35WXedfnafUmXKbCJchqVKlWWJbjgsODmWFF8MJON3mWRc6TFz+GHbyPruBTt3k6Z97yGO8X3bgZXmaCnYaV6nEeIY9wdrBhw57xbOty8oeYfLYxVIiNdSVjN+6qSLG2NLQP7ujGVk0lYge0ruXFks2F9W7owoD0uRGTqhD88I5J4DMeWlqTbZH6q8V3dZ37Cwpn/MkrlmdonUs2hs70xrIhQXpn3KzveSIZWHsWpRkFBBTseQMEiXD2ARa+pApQbcZCcnee5isC/BC6LgZQ3OOWtHvAdPCgM2GaqveaMGFfwV+iTFqxS/j0bRqATjEUHTID3kV5e0lEoAJXWAmcuu736+l2DZeKvG1yJGSDp+DPE2zJaEBInDnypMbzvVCt2VAdMHVA1nbmad55o81XLGek6MbMui5ZjXRnmJjwYsxkkd1vAttMUBvseog5xqq6XhXd86eQnJ8qrF1Qtn2KYmpbZxu004yV2odXqIU57K7TniRZi+vuyk0eyJ2ul0=}
bot:
  automerge: true
